# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Build and Test

on: [push, pull_request]

jobs:
  debian:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [8, 11, 17]
        codes: [ 'uncompressed,brotli', 'gzip,snappy' ]
        include:
        - jdk: 8
          title: AMD64 Debian 9 Java JDK 8 Maven 3.5.4
          maven: 3.5.4
          image: debian-java
        - jdk: 11
          title: AMD64 Debian 9 Java JDK 11 Maven 3.6.2
          maven: 3.6.2
          image: debian-java
        - jdk: 17
          title: AMD64 Oracle Linux Server 8.5 Java JDK 17 Maven 3.8.5
          maven: 3.8.5
          image: oracle-java
    name: Build Parquet with JDK ${{ matrix.title }} and ${{ matrix.codes }}
    env:
      JDK: ${{ matrix.jdk }}
      MAVEN: ${{ matrix.maven }}
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: before_install
        env:
          CI_TARGET_BRANCH: $GITHUB_HEAD_REF
        run: |
          bash dev/ci-before_install.sh
      - name: install
        run: |
          EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs -q -DforceStdout)
          export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"
          mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true -Djava.version=${{ matrix.jdk }}
      - name: verify
        env:
          TEST_CODECS: ${{ matrix.codes }}
          JAVA_VERSION: ${{ matrix.jdk }}
        run: |
          EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs -q -DforceStdout)
          export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"
          mvn verify --batch-mode javadoc:javadoc -Pci-test
